### ISSUE TITLE
Required Old Twitter Logo Update | 'X'

### ISSUE THREAD

**Issue by yuvrajsingh-kiwi** [MurhafSousli/ngx-sharebuttons#657]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-sharebuttons

Steps to reproduce:
1.  Just check the logo of the Twitter Share Button

#### Expected Behavior

What behavior were you expecting to see?
New Logo Of Twitter 'X'

#### Actual Behavior

What behavior did you actually see?
Old Logo Of Twitter Button

#### Environment

- Angular: 14
- ngx-sharebuttons: 13
- Browser(s): Chrome Latest
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

**Comment by AshotAleqsanyan96** [comment]
@yuvrajsingh-kiwi please check https://github.com/MurhafSousli/ngx-sharebuttons/issues/650 they already have a PR, we are also waiting for this change.

**Comment by MurhafSousli** [comment]
To can change the icon from the global options like so:

```scss

import { faXTwitter } from '@fortawesome/free-brands-svg-icons';
import { FaIconLibrary, } from '@fortawesome/angular-fontawesome';

@NgModule({
  imports: [
    ShareButtonsModule.withConfig({
      debug: true,
      prop: {
        twitter: {
          icon: ['fab', 'x-twitter'],
          color: '#1E3050',
        }
      }
    })
  ],
})
export class AppModule {
  constructor(iconLibrary: FaIconLibrary) {
    iconLibrary.addIcons(faXTwitter);
  }
}

```

Here is a stackblitz: https://stackblitz.com/edit/ngx-sharebuttons-6hfmg3?file=src%2Fapp%2Fapp.module.ts
